# Generated by Django 4.2.3 on 2023-07-17 14:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('diameter', models.CharField(max_length=255)),
                ('rotation_period', models.CharField(max_length=255)),
                ('orbital_period', models.CharField(max_length=255)),
                ('gravity', models.CharField(max_length=255)),
                ('population', models.CharField(max_length=255)),
                ('climate', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
