# Generated by Django 4.2.3 on 2023-07-18 17:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='user_id',
            new_name='id',
        ),
        migrations.AddField(
            model_name='favorite',
            name='user_identifier',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='custom_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
