# Generated by Django 4.2.3 on 2023-07-18 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('favorites', '0002_rename_user_id_favorite_id_favorite_user_identifier_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user_identifier', 'object_id', 'content_type')},
        ),
    ]
