# Generated by Django 4.2.3 on 2023-07-17 09:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('release_date', models.DateField()),
                ('director', models.CharField(max_length=100)),
                ('episode_id', models.IntegerField(null=True)),
                ('opening_crawl', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
